### ISSUE TITLE
Not obvious that sidebar panel can be scrolled

### ISSUE THREAD

**Issue by audionerd** [wonderunit/storyboarder#1084]
The sidebar, which contains the Shot Generator, can be scrolled. But it's not obvious enough to users.

We could try adding a small down arrow at the bottom, where the fade overlay is. If a user clicks it, it scrolls down all the way to the bottom. If a user scrolls manually more than 10px or so, maybe the down arrow fades out.

TASKS
- [x] Add arrow on overlay. 
- [x] If "Shot Generator" is available, add to "Tools" menu. Triggers scroll.
- [x] Shot Generator visually explains why it has been disabled if WebGL is not available.
- [x] Click arrow to scroll down.
  - [x] Overlay might have to trap click events?
- [ ] Arrow is too stout

**Comment by boudreaupaul** [comment]
This is a very good idea. My opinion is that this is one of the largest reasons beginners would initially choose storyboarder, even though I would say that once they realize the other features they would come to love it for other features just as much. You do a great job of advertising the feature on your main website but since this is a common (fairly common?) question maybe the scroll thing should be mentioned in the advertising of the feature? That's where I went first to research my problem with this. Maybe just a sentence that says "Just scroll down and enjoy quick generation of scenes" or something similar.

**Comment by ichbinmatthias** [comment]
wow - i just scrolled down for the first time after using storyboarder for about a month... o_O

**Comment by setpixel** [comment]
it's like the gift that keep on giving! ^_^

**Comment by audionerd** [comment]
Got a fix for this. Will be part of the next release.
