### ISSUE TITLE
Artist should be able to select target for image import (new board vs. current board)

### ISSUE THREAD

**Issue by audionerd** [wonderunit/storyboarder#1214]
There are three ways to bring an image in:

1) "File > Import Image"
2) Drag image to window
3) Mobile image import

Right now, 1 & 2 go to a new board, 3 goes to current board.

We should allow the artist to select which method they prefer, and remember it. Possibly a dialog box on first use, and remember the setting in prefs after that? Or just a prefs setting to start?

Related to https://github.com/wonderunit/storyboarder/issues/381

**Comment by gordielachance** [comment]
I don't think this is a good solution because 
- no one likes too much dialog box 
- you don't always import images the same way : once you'll need to import it to current board, another time you'll need to import it as new shot.

About importing an image to the current board, see https://github.com/wonderunit/storyboarder/issues/853#issuecomment-399150182

**Comment by setpixel** [comment]
Yeah I think we need two menu options per gordie's point: 

Import Image(s) as new boards
Import Image into current board

**Comment by audionerd** [comment]
Implemented in https://github.com/wonderunit/storyboarder/pull/1279
