### ISSUE TITLE
Playback issue

### ISSUE THREAD

**Issue by Albois** [wonderunit/storyboarder#1355]
Hi, Playback won't stop using space bar or clicking on buttons.
At first it works for 10 to 15 boards but then it just doesn't stop.
This bug is quite random. Sometimes spacebar works other times not.

Also. Changing the board timing doesn't change playback. If I want a slow playback it just isn't possible. Be it 500 or 5000.

**Comment by audionerd** [comment]
Hmm, that's odd. Maybe it's switching to panning mode? When you're zoomed in, <kbd>spacebar</kbd> will control the panning tool _instead_ of playback. In panning mode you'll see a grabby hand cursor instead of the brush cursor. Could that be the problem?

Re: board timing: changing the board timing for a single board only changes that board. It won't change other boards. Do you mean that during playback, the durations are being entirely ignored by Storyboarder?

**Comment by Albois** [comment]
Yes it is strange.
Just tried it again usisng only the transport buttons.

Transport buttons works for the first 20 board then it doesn't work any more.
I press play and it won't stop after pressing pause.

I have the impression that it is working hard to play through the board and it can't process when I press pause.
I can send you a short screen movie.

And no it is not in panning mode.

As for the duration it is always the same. The number I put in here has no effect.



Anything you want me to try?

**Comment by Albois** [comment]
It is still happening. Playback goes on once it started. Even if I press pause it won't stop.

**Comment by audionerd** [comment]
This should be fixed in the upcoming release of Storyboarder.
