### ISSUE TITLE
On Mac OS icons don't seem to work and working area is too big

### ISSUE THREAD

**Issue by Costello8** [wonderunit/storyboarder#156]
When using the Darwin binary and launching on Mac OS the working area is bigger than the screen (so you can't see all of the icons). Also none of the toolbar icons seem to have any effect. I've tried this on two different Macs now one with Retina screen and one without, both running 10.12

**Comment by setpixel** [comment]
We have a new build coming soon... we've been working on trying to get it out soon.

**Comment by vxfmatt** [comment]
THANK YOU!
THANK YOU!
Come on man you can do it i just found you and i cried when it didnt work for me

**Comment by setpixel** [comment]
Don't cry buddy! Check this out: https://www.youtube.com/watch?v=7yKvn3h0ivU

**Comment by setpixel** [comment]
Thanks!! Please continue to send feedback, ideas, or anything!!! Seriously!

**Comment by DCNielsen** [comment]
Digging this beta. This is a sweet lightweight tool and as it shapes up I think it's going to be better than Photoshop for a storyboard workflow. 

Here are some ideas: 
I watched a video awhile back of Robert Valley and his technique involves drawing thumbnails really small (like the size of a quarter). This increases storyboarding speed exponentially, and you can still do a clean-up pass later. Whatever zoom-out you're planning could account for this, so long as it's easy to say, work at 25%, cycle through panels, move them around, etc. and then just zoom in later for cleanup.

In the alpha, I could copy the frame I was working on to the clipboard, pass to Photoshop via a paste, use Photoshop tools, then copy paste back to Storyboarder. In the beta, when I try to do that, I seem to be getting a screened back version in Photoshop. However, it looks like you're working on something that will let you jump straight to photoshop, save and go right back to where you were, so that's cool.

I like the auto-voice reading. Are there other voices available? What if you could assign a voice per character somehow? Maybe per panel?

Also, what about a comic-book mode? Likely out of scope, but it could be pretty cool to figure out something that allows you to fluidly go back and forth between composing the page and working within a panel. For example, you could start in a thumbnail composition view that shows the whole page. There's a tool to divide the page up into panels. Draw wherever you want on this composition view but the panels automatically get reproduced as individual panels in order, auto-referencing larger images at the right ratios. Thumbnail Comp Page 1 generates> Panel A > Panel B > Panel C. Then you go and draw in the referenced panels, go back and check the composition, rescale some panels, etc. Once you get stuff dialed in you could spit it out to pencil over with real pencils or in Photoshop.

Anyway, love it so far. Thanks for putting it out there.

**Comment by setpixel** [comment]
Hi @DCNielsen 

Thanks for the thoughtful feedback! Are you a storyboard artist for animation or comic book artist?

Re: Thumbnailing: Totally on board with this idea. I hadn't seen that video before, but I just watched it. Really cool. We will have a couple ideas to solve for this problem.

1) We will definitely have the ability to zoom out to small sizes. Probably standard photoshop key commands: cmd+=, cmd+-, cmd+0
2) There will be an ability to print out a storyboard worksheet, draw on it with pen/pencil, and easily scan it back in with your phone. You can configure the size of the boards on the sheet. Please watch this video for a demo: https://youtu.be/mendVVdY1ps?t=3m4s

Re: Voice reading: Probably won't be able to set the voice. At least not for a while. We would like to support ability to stub your own recordings before I spend more time on robo voices. But for now, most of the focus is on the visual aspects.

Re: Comic books: Great idea! Totally out of scope for us, but nothing is stopping someone from forking the code :D I think there is some comic layout software already. You could board quickly, export all the art, and then just import it into that other software. 

How did you find this software?

**Comment by DCNielsen** [comment]
I do a little bit of both, but not "in the industry". My day-job has alternated between UX and graphic design but explainer video content has given me some story opportunities. My time is pretty limited for personal projects, so I keep an eye out for tools and techniques that can help me get things done fast.

That print and scan feature looks incredible. Can't wait to work with that. 

Even without a comic layout feature, Storyboarder is still workable to rough a comic's story flow even though I can't work the whole page's composition, at least it gets things blocked visually and then I can rework everything with the whole page in mind.

Do you guys have anything planned for camera moves? For example, I can add an additional screen width to the right. Maybe when the frame switches, there's a pan and I can set how quick it goes? Less linear movement gets trickier.

I did a google search for lightweight, opensource storyboarding software and found Storyboard Fountain which led me to Storyboarder.
