### ISSUE TITLE
Why cannot I not "

### ISSUE THREAD

**Issue by hnmathews** [wonderunit/storyboarder#2026]
Please help, I am making edits and need to save as a new file name I get this error saying I can't why? 
<img width="410" alt="Screen Shot 2020-05-30 at 2 53 47 PM" src="https://user-images.githubusercontent.com/66142683/83339762-bc328900-a285-11ea-9e0b-7a974314ecfe.png">

**Comment by audionerd** [comment]
Thanks for the report. Did you use Shot Generator to make any boards? Looks like Storyboarder is trying to find a shot generator camera plot and can't locate it.

As a short term solution, instead of using the Save As feature, you could try making a copy of the project folder (containing the .storyboarder file and images folder etc) and then rename it on the filesystem instead.

Closing for now as this is related to an already known issue #1155.
