### ISSUE TITLE
Keyboard Shortcut - Storyboarder

### ISSUE THREAD

**Issue by tnaruoc** [wonderunit/storyboarder#2285]
Hello,

First of all, I want to thanks for this software Storyboarder available for free, it's very kind, useful for student and professional ! :)
I've just a little bug, I can't change my Keyboard Shortcut. But maybe it's not possible, I'm waiting your feed back.

Have a nice day
Estelle

**Comment by audionerd** [comment]
It is possible to change which key combinations are mapped to each keyboard command. You can reveal the keymap file from Storyboarder’s Preferences. It's a JSON data file that can be edited in a code editor like Visual Studio Code. You'll have to restart Storyboarder for the change to take effect.

Which keyboard shortcut do you want to change? What have you tried so far to change it? What happens when you try?

**Comment by tnaruoc** [comment]
> It is possible to change which key combinations are mapped to each keyboard command. You can reveal the keymap file from Storyboarder’s Preferences. It's a JSON data file that can be edited in a code editor like Visual Studio Code. You'll have to restart Storyboarder for the change to take effect.
> 
> Which keyboard shortcut do you want to change? What have you tried so far to change it? What happens when you try?

**Comment by tnaruoc** [comment]
Okey, I thought it was directly possible in the soft but I'll try with your solution, thank you very much ! :)
