### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jminor** [wonderunit/storyboarder#567]
What license is this source code available under?

**Comment by TeddyDD** [comment]
"By default" everything you publish is considered **All rights reserved**

Do you guys have plans to [choose](https://choosealicense.com/) any FOSS license? It seems that you have no plans to monetize Storyboarder (according to your website) so I guess that would be good way to go.

**Comment by alexwidener** [comment]
Hey @jminor !

> "license": "ISC",

is what's listed in the package.json.

**Comment by setpixel** [comment]
Hi guys, I really haven't thought about the Lic much. TBH, It's been a while since I've read up on it. Do you guys have any suggestions?

**Comment by alexwidener** [comment]
[MIT](https://tldrlegal.com/license/mit-license) is probably going to be the most popular, I'd say.

**Comment by jminor** [comment]
MIT, BSD and Apache licenses are all common and permissible, which make them more agreeable for collaboration with a wide range of use cases. The guidance at the site @TeddyDD linked (https://choosealicense.com) seems to match what I've encountered previously.

**Comment by TeddyDD** [comment]
@setpixel I'd suggest you to take a look at https://choosealicense.com/ 

You have to be careful when choosing license since it might hard or impossible to change it afterwards (example: you have to have [CLA](https://en.wikipedia.org/wiki/Contributor_License_Agreement) signed by all contributors to re-license copyleft project under GPL). If you don't wan to deal with then best bet is BSD or MIT license. 

I know all that law stuff sucks. Personally I'm artist not lawyer but feel free to ask any questions, I'll help if I can 😃

**Comment by ideasman42** [comment]
Hi, I reported #588.
While ideally you might want to choose the license that perfectly fits your own preference.
It's generally least hassles to choose a license thats used by code you're likely to use/inter-operate with.
Otherwise someone may see that your application+deps uses many licenses and checking if there are any gotcha's becomes a chore.

Suggest to check the licenses use by code you depend on and other libs in NPM.

From a quick check, 2 of the 3rd party deps use MIT (which is a popular license and [functionally equivilant to ISC](https://choosealicense.com/licenses/isc/)).

**Comment by TeddyDD** [comment]
ISC is nice license, but key: value in package.json is not enough. As you can see in [tldr legal](https://tldrlegal.com/license/-isc-license) you have to include the full text of license in modified software. Witch is impossible if Storyboarder does not have license text in repo 😉 I think instead #589 you should create LICENSE.txt in the repo root with ISC license text
```
Copyright <YEAR> <OWNER>

Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
```
It's better to keep license file separated from readme since then it's easier to package your program.
