### ISSUE TITLE
JavaScript error when open .fountain file.

### ISSUE THREAD

**Issue by CoIin** [wonderunit/storyboarder#706]
The attached file was written with this app: https://itunes.apple.com/us/app/writer-free-fountain-screenwriting-tool/id1046973568?mt=12

It's quite likely there is a formatting issue, but it should still not cause a JavaScript error:

Uncaught Exception:
TypeError: Cannot read property 'replace' of undefined
    at processFountainData (/Applications/Storyboarder.app/Contents/Resources/app.asar/src/js/main.js:358:35)
    at fs.readFile (/Applications/Storyboarder.app/Contents/Resources/app.asar/src/js/main.js:261:29)
    at tryToString (fs.js:513:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:501:12)

Start a new Storyboarder document, from the attached file.

[Untitled.fountain.zip](https://github.com/wonderunit/storyboarder/files/1326292/Untitled.fountain.zip)

**Comment by audionerd** [comment]
I’ll add better error handling so that users will be notified if a script fails to load.

The attached script has no title, which Storyboarder requires. But I’ll change the code to handle this by defaulting to the filename as the title.

The attached script also has no defined scene. I'm not sure how Storyboarder should handle this. Tracking that bug here: https://github.com/wonderunit/storyboarder/issues/719
