### ISSUE TITLE
In need of pen pressure solution for storyboarder THAT WORKS FOR WINDOWS 7

### ISSUE THREAD

**Issue by superpunksuperfunk** [wonderunit/storyboarder#727]
Im looking for help with the broken pen pressure problem with storyboarder.

I use windows 7 which means I do not have windows ink. 

I have reinstalled my wacom tablet but nothing so far is working

**Comment by CuberToy** [comment]
Personal feeling here. Avoid the caps.
Now note that Storyboarder is still in BETA. Those issues will surely get fixed in the future by the devs.

Would believe it's a chromium issue (pen pressure on Win was unavailable for a long time...). I guess you'll have to be patient if no workaround works for you.

**Comment by audionerd** [comment]
@superpunksuperfunk can you post the make/model of the pen tablet you're using?

We have a user-reported list of pens that are known to work (and not work) here: https://github.com/wonderunit/storyboarder/wiki/Previously-Answered-Questions

The Storyboarder app is built on the Chromium and Electron libraries, and those libraries actually have the code for pen support. Hopefully as those libraries continue to be updated in the future, we'll get better support in Storyboarder as well. It might take some time though.

**Comment by setpixel** [comment]
I'm afraid we cannot support windows 7. Sorry :(

Please see #690 for pen issues support
