### ISSUE TITLE
What format of script is importable? Final Draft and PDF don't import.

### ISSUE THREAD

**Issue by WarrenLE** [wonderunit/storyboarder#744]

**Comment by CuberToy** [comment]
For the moment, you can import Fountain screenplay.
If you wrote in Final Draft, some software out there can convert your script to fountain.

On a more personal note, I would recommend to stop using Final Draft altogether, even though it's the standard because it's been around for decades, it's pretty shitty.

Free (you can convert final draft to fountain here) : https://kitscenarist.ru/en/index.html
One time low price (and personal favorite) : https://www.fadeinpro.com/

**Comment by setpixel** [comment]
You can open a Final Draft script in the current version now! 👍
