### ISSUE TITLE
Storyboarder does not work on Windows 10

### ISSUE THREAD

**Issue by Khemardi** [wonderunit/storyboarder#758]
I'm running windows 10. I downloaded and installed Storyboarder just fine. But when I try to open the program, nothing happens. I see that the program is running in task manager, but the weird thing is there are two instances of it. one using less memory than the other. Whenever I right click to analyze wait chain in task manager it says; "One or more threads of Storyboarder.exe are in waiting status."

I can't figure this out, I assumed another program was blocking it somehow, so I killed every program I could and tried to open Storyboarder again, but with the same result. I even tried giving it priority over other programs but still nothing. I would be happy if I could at least look at the splash screen or something... but the program just will not open. Oh I also tried reinstalling and restarting my machine. Still nothing

**Comment by setpixel** [comment]
Hi @Khemardi this is very odd! I need to think about how to approach figuring this out.

**Comment by Khemardi** [comment]
ok, thank you. in the mean time, i'll be trying to figure it out as well

**Comment by Khemardi** [comment]
ok, so I got it to open. It works if it's the first thing I open as soon as I log on to the pc. But when I close the app, and try to re-open, it doesn't open. So for now the only way to use it, is if I restart my pc, then execute it before anything else >.> *sigh* that's not very efficient

**Comment by TimTeamer** [comment]
Old thread, but thought I'd post, since it was high on google's search and others may run into the same issue. I have (at this time) the latest v1903 Windows 10 build. It won't save panel art, it won't let you draw when you open a saved item, it won't launch Photoshop... it's useless, but I just tried it on a friends v1803 build and EVERYTHING works perfectly! I happen to have a v1809 Windows 10 image and will try installing it on there. If it works, I may/may-not report back. But, how or when do these updates happen... I need to learn coding to give a hand... I can only test at the moment I guess. Looks like GREAT software, Thanks! I hope to become a loyal user (this is my first time).

**Comment by tigyii** [comment]
solved my own issue. Pretty unique, but maybe this will help some others that encounter similar issues?

https://github.com/wonderunit/storyboarder/issues/1699

**Comment by Shyam323** [comment]
I'm facing problem with shot generator, i am not able to add characters in shot generator, even software also not looking like in youtube, how can i solve it.
