### ISSUE TITLE
UI discoverability (e.g.: "artists can't find the shot generator")

### ISSUE THREAD

**Issue by audionerd** [wonderunit/storyboarder#806]
A lot of users don't realize, for example, that you can scroll down to get to the Shot Generator.

Could have some kind of onboarding/training to improve discoverability? Video demo?
Maybe Shot Generator should be in a tab, so it's seen earlier?

**Comment by scottpetrovic** [comment]
As a UI person, people don't generally read how to use an application when they are learning. Educational material  is a great idea and it is necessary for more advanced concepts or technical things, but most beginning artists I know like to just "jump in and see how easy it is to figure it out!". I have seen so many videos of people using this approach that I think you should try your damnedest to get a clear UI without having to rely on documentation to understand.

My view on this specific issue -- I think the reason why it isn't obvious is because of how that area is presented on the UI. That area is seamlessly shown with all the other features in the application. No other area can scroll so why would be people think that the area on the right could be scrollable? If I was in charge of the UI, I would make that entire right area seem more like its own section. At the least put a hint of a left border to show it is indeed a separate section of the application. The slight gradient at the bottom is a small visual cue that there is more below, but the content doesn't cut off enough to make it obvious that it can be scrollable.

**Comment by setpixel** [comment]
Fixed in #1089
