### ISSUE TITLE
"Import images" should allow to import individual files instead of a directory

### ISSUE THREAD

**Issue by gordielachance** [wonderunit/storyboarder#864]
Hi !
It would be better if we were allowed to select (multiple) images in a directory rather than importing a whole directory.

1. it would allow to import a single (or multiple) images
2. it would avoid errors "OOps! There was a problem importing..." when a file from the directory is not a valid image file (eg. not an image file)

Eventually there could be two menus : _import images directory_ and _import images_.

Thanks!

**Comment by audionerd** [comment]
"Import Images" shows a file selection dialog where you can hold "shift" to select multiple images to import. You can also drag multiple images onto the timeline to import them.

**Comment by audionerd** [comment]
Related to https://github.com/wonderunit/storyboarder/issues/867

**Comment by amedeux** [comment]
When either "Import Images to New Boards..." or "Import Image and Replace..." are selected, the software only allows to chose folders instead of simple pictures, which are not listed.

In the first case it'll import all the images, in the second case it will import only the first one of the folder (alphabetically listed). This happens on a Win7 machine.

I'd have expected to be able to select a single picture or multiple ones, like @audionerd  is suggesting before closing the post.
