### ISSUE TITLE
Export to Clip Studio failed

### ISSUE THREAD

**Issue by theDesuDesu** [wonderunit/storyboarder#919]
Hello good folks of wonderunit,

i wanted to export a board to Clip Studio Paint as a test - i usually export to Sai and i works like a charm - and i got an error 'unsupported file format". Normally psd's should open In Clip but from what i could gather this could be because the psd is 16 bit instead of 8bit. Apparently Clip can't handle 16bit. Now i don't have Photoshop to check this so any clarification is appreciated.

**Comment by setpixel** [comment]
Hi @theDesuDesu !

So we only create psds that are 8bpp. So I dont think that's it. 

I think the newest version of clip studio introduced this problem... I think that older versions work. I dont know exactly what to do because there is no detailed error warning from clip studio.

Can you email clip studio and send them the .psd?

-c

**Comment by setpixel** [comment]
OK! I fixed it! woohoo.

I'll spare you the details, but I'm pushing up a release tonight!

**Comment by theDesuDesu** [comment]
Oh hey thats awesome! Thanks man, this means a lot!

2017-12-07 0:53 GMT+01:00 Charles Forman <notifications@github.com>:
